name: Deploy website to FTP

on:
  push:
    branches:
      - main
      - master # Triggers deployment when you push to main or master branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚙️ Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Update npm & Install dependencies
      run: |
        npm install -g npm@latest
        rm -f package-lock.json
        rm -rf node_modules
        npm install --include=optional

    - name: 🏗️ Build static production files
      run: npm run build

    - name: 🚀 Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # The build output is compiled inside the 'dist' directory
        local-dir: ./dist/
        # The target subdirectory on your FTP server (using your newly added FTP_SERVER_DIR secret)
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        # Set to true if you want to delete any existing files on the FTP server that aren't in dist/
        dangerous-clean-cut: false
